### ISSUE TITLE
bug in PeriodicGrid2DTopBottom when run in parallel

### ISSUE THREAD

**Issue by JamiePringle** [usnistgov/fipy#1080]
I have found what appears to be a bug in PeriodicGrid2DTopBottom when run in parallel with MPI. It runs fine with closed boundaries. The minimum code to reproduce it is 
```
from mpi4py import MPI
from fipy import CellVariable, Grid2D, Viewer, TransientTerm, DiffusionTerm, FaceVariable,PowerLawConvectionTerm,PeriodicGrid2DTopBottom,PeriodicGrid2DLeftRight

if __name__ == '__main__':

    #make dimensions
    nx=512*3
    ny=512*3+128
    Lx=float(nx-1)*1e3
    Ly=float(ny-1)*1e3
    dx=Lx/(nx-1)
    dy=Ly/(ny-1)

    #get rank to figure out what is up
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    
    #This is cobled together from the fipy examples to solve the poisson equation
    print('making mesh','rank',rank,flush=True)
    mesh = PeriodicGrid2DTopBottom(dx=dx, dy=dy, nx=nx, ny=ny)
    
    print('   done making mesh, rank',rank)
```

When run in serial it works fine. But when run in parallel with `OMP_NUM_THREADS=1 mpirun -np 4 python demonstrate_PeriodicGrid2DTopBottom_bug.py` rank  0 crashes with 

```
Traceback (most recent call last):
  File "/data/plumehome/pringle/workfiles/ATWnew/try01/demonstrate_PeriodicGrid2DTopBottom_bug.py", line 22, in <module>
    mesh = PeriodicGrid2DTopBottom(dx=dx, dy=dy, nx=nx, ny=ny)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pringle/miniconda3/envs/fipy2024/lib/python3.12/site-packages/fipy/meshes/periodicGrid2D.py", line 21, in __init__
    self._makePeriodic()
  File "/home/pringle/miniconda3/envs/fipy2024/lib/python3.12/site-packages/fipy/meshes/periodicGrid2D.py", line 113, in _makePeriodic
    self._connectFaces(numerix.nonzero(self.facesBottom),
  File "/home/pringle/miniconda3/envs/fipy2024/lib/python3.12/site-packages/fipy/meshes/abstractMesh.py", line 218, in _connectFaces
    assert numerix.allclose(numerix.take(self._areaProjections, faces0, axis=1),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pringle/miniconda3/envs/fipy2024/lib/python3.12/site-packages/fipy/tools/numerix.py", line 564, in allclose
    return MA.allclose(first, second, atol=atol, rtol=rtol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pringle/miniconda3/envs/fipy2024/lib/python3.12/site-packages/numpy/ma/core.py", line 8182, in allclose
    m = mask_or(getmask(x), getmask(y))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pringle/miniconda3/envs/fipy2024/lib/python3.12/site-packages/numpy/ma/core.py", line 1757, in mask_or
    return make_mask(umath.logical_or(m1, m2), copy=copy, shrink=shrink)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: operands could not be broadcast together with shapes (2,1,0) (2,1,1536) 
```

Python 3.12.7, fipy version 3.4.5

Thanks,
Jamie Pringle
University of New Hampshire

**Comment by guyer** [comment]
Unfortunately, this has been broken for awhile (#518). At one point, I was making progress on fixing it, but it hasn't gotten the attention it needs.

**Comment by guyer** [comment]
I'm in the middle of a major effort with solver suites, but once I'm done with that I'll try to finish fixing #518; it affects some work I want to do, too.

**Comment by JamiePringle** [comment]
Thank you
Jamie
