### ISSUE TITLE
Intermittent failure in `_BinaryTerm` parallel tests

### ISSUE THREAD

**Issue by guyer** [usnistgov/fipy#310]
Only sometimes, and only on some platforms, we get [http://build.cmi.kent.edu:8010/builders/Mac_OS_X%7Etrunk%7Efull/builds/13/steps/trial_2/logs/problems failures] in `_BinaryTerm`

``` python
======================================================================
FAIL: _test (fipy.terms.binaryTerm._BinaryTerm)
Doctest: fipy.terms.binaryTerm._BinaryTerm._test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fipy/.homebrew/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 2166, in runTest
raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for fipy.terms.binaryTerm._BinaryTerm._test
  File "/Users/fipy/.virtualenvs/buildbot/build/fipy-buildbot/fipy-build/Mac_OS_X~trunk~full/build/fipy/terms/binaryTerm.py", line 112, in _test

----------------------------------------------------------------------
File "/Users/fipy/.virtualenvs/buildbot/build/fipy-buildbot/fipy-build/Mac_OS_X~trunk~full/build/fipy/terms/binaryTerm.py", line 169, in fipy.terms.binaryTerm._BinaryTerm._test
Failed example:
print CellVariable(mesh=m, value=value)
Expected:
[ 0.  0.  0.  0.  0.  0.]
Got:
[ 0.  0.  1. -2.  0.  0.]
```

 _Imported from trac ticket [#430](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/430),  created by guyer on 01-31-2012 at 17:45, last modified: 01-31-2012 at 17:45_

**Comment by guyer** [comment]
Works now
