### ISSUE TITLE
Error message for bad NumPy itemset has changed

### ISSUE THREAD

**Issue by guyer** [usnistgov/fipy#374]
With NumPy 1.7.0, we now get an error due to a changed error message upon a bad `itemset`:

``` python

======================================================================
FAIL: itemset (fipy.tools.dimensions.physicalField.PhysicalField)
Doctest: fipy.tools.dimensions.physicalField.PhysicalField.itemset
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../python/2.7.2/lib/python2.7/doctest.py", line 2166, in runTest
raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for fipy.tools.dimensions.physicalField.PhysicalField.itemset
  File ".../fipy/tools/dimensions/physicalField.py", line 577, in itemset

----------------------------------------------------------------------
File ".../fipy/tools/dimensions/physicalField.py", line 587, in fipy.tools.dimensions.physicalField.PhysicalField.itemset
Failed example:
a.itemset(PhysicalField("6 ft"))
Expected:
Traceback (most recent call last):
...
ValueError: can only place a scalar for an  array of size 1
Got:
Traceback (most recent call last):
File ".../python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
compileflags, 1) in test.globs
File "<doctest fipy.tools.dimensions.physicalField.PhysicalField.itemset[4]>", line 1, in <module>
a.itemset(PhysicalField("6 ft"))
File ".../fipy/tools/dimensions/physicalField.py", line 600, in itemset
self.value.itemset(value)
IndexError: index 511 is out of bounds for axis 0 with size 2
```

 _Imported from trac ticket [#556](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/556),  created by guyer on 03-20-2013 at 16:49, last modified: 03-20-2013 at 16:51_

**Comment by guyer** [comment]
Fixed ages ago (51a5edae)
