### ISSUE TITLE
Gmsh 2.11 breaks GmshGrids

### ISSUE THREAD

**Issue by guyer** [usnistgov/fipy#488]
With Gmsh 2.11 (and maybe earlier), the `GmshGrid` tests fail:

``` python
======================================================================
FAIL: _test (fipy.meshes.gmshMesh.GmshGrid2D)
Doctest: fipy.meshes.gmshMesh.GmshGrid2D._test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/guyer/anaconda/envs/test-environment5/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for fipy.meshes.gmshMesh.GmshGrid2D._test
  File "/Users/guyer/Documents/research/FiPy/fipy/fipy/meshes/gmshMesh.py", line 2188, in _test

----------------------------------------------------------------------
File "/Users/guyer/Documents/research/FiPy/fipy/fipy/meshes/gmshMesh.py", line 2199, in fipy.meshes.gmshMesh.GmshGrid2D._test
Failed example:
    numerix.allclose(yogmsh._faceAreas, yogrid._faceAreas) # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/Users/guyer/Documents/research/FiPy/fipy/fipy/meshes/gmshMesh.py", line 2202, in fipy.meshes.gmshMesh.GmshGrid2D._test
Failed example:
    yogmsh.cellCenters.value.size == yogrid.cellCenters.value.size # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/Users/guyer/Documents/research/FiPy/fipy/fipy/meshes/gmshMesh.py", line 2207, in fipy.meshes.gmshMesh.GmshGrid2D._test
Failed example:
    mesh.numberOfCells == 4 # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/Users/guyer/Documents/research/FiPy/fipy/fipy/meshes/gmshMesh.py", line 2210, in fipy.meshes.gmshMesh.GmshGrid2D._test
Failed example:
    len(mesh.faceCenters[0]) == 12 # doctest: +GMSH
Expected:
    True
Got:
    False


======================================================================
FAIL: _test (fipy.meshes.gmshMesh.GmshGrid3D)
Doctest: fipy.meshes.gmshMesh.GmshGrid3D._test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/guyer/anaconda/envs/test-environment5/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for fipy.meshes.gmshMesh.GmshGrid3D._test
  File "/Users/guyer/Documents/research/FiPy/fipy/fipy/meshes/gmshMesh.py", line 2262, in _test

----------------------------------------------------------------------
File "/Users/guyer/Documents/research/FiPy/fipy/fipy/meshes/gmshMesh.py", line 2276, in fipy.meshes.gmshMesh.GmshGrid3D._test
Failed example:
    yogmsh.cellCenters.value.size == yogrid.cellCenters.value.size # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/Users/guyer/Documents/research/FiPy/fipy/fipy/meshes/gmshMesh.py", line 2279, in fipy.meshes.gmshMesh.GmshGrid3D._test
Failed example:
    numerix.allclose(yogmsh._faceAreas, yogrid._faceAreas) # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/Users/guyer/Documents/research/FiPy/fipy/fipy/meshes/gmshMesh.py", line 2282, in fipy.meshes.gmshMesh.GmshGrid3D._test
Failed example:
    numerix.allclose(yogmsh._faceAreas, yogrid._faceAreas) # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/Users/guyer/Documents/research/FiPy/fipy/fipy/meshes/gmshMesh.py", line 2291, in fipy.meshes.gmshMesh.GmshGrid3D._test
Failed example:
    len(mesh.cellCenters.value[0]) == 8 # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/Users/guyer/Documents/research/FiPy/fipy/fipy/meshes/gmshMesh.py", line 2298, in fipy.meshes.gmshMesh.GmshGrid3D._test
Failed example:
    nx.allclose(mesh._faceAreas, faceAreas) # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/Users/guyer/Documents/research/FiPy/fipy/fipy/meshes/gmshMesh.py", line 2308, in fipy.meshes.gmshMesh.GmshGrid3D._test
Failed example:
    nx.allclose(mesh._cellAreas, cellAreas) # doctest: +GMSH
Expected:
    True
Got:
    False


----------------------------------------------------------------------
```

**Comment by KDra** [comment]
It fails for me too. I tried everything: system wide, anaconda virtual environment, from source, pip, different versions of gmsh. The test fails but so does a custom script where I use gmsh commands or when I use a .msh file.
The deb installation of fipy also did not work.
I am using linux mint 17.3 (based on ubuntu 14.04)
