### ISSUE TITLE
Gmsh call errors

### ISSUE THREAD

**Issue by KDra** [usnistgov/fipy#494]
When running the http://www.ctcms.nist.gov/fipy/examples/diffusion/generated/examples.diffusion.circle.html tutorial i get the following error and output:

"
Traceback (most recent call last):

  File "<ipython-input-1-b1aad4ad4266>", line 1, in <module>
    runfile('/home/user/test/fipy/rotCyl.py', wdir='/home/user/test/fipy')

  File "/home/user/anaconda3/envs/fipy/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 714, in runfile
    execfile(filename, namespace)

  File "/home/user/anaconda3/envs/fipy/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
    builtins.execfile(filename, *where)

  File "/home/user/test/fipy/rotCyl.py", line 30, in <module>
    CylMesh = Gmsh2D('cylinder.geo', communicator=serialComm)

  File "/home/user/anaconda3/envs/fipy/lib/python2.7/site-packages/FiPy-3.1.dev137_g92a21a0-py2.7.egg/fipy/meshes/gmshMesh.py", line 1579, in __init__
    self._orderedCellVertexIDs_data) = self.mshFile.read()

  File "/home/user/anaconda3/envs/fipy/lib/python2.7/site-packages/FiPy-3.1.dev137_g92a21a0-py2.7.egg/fipy/meshes/gmshMesh.py", line 803, in read
    raise GmshException(errStr)

GmshException: Gmsh hasn't produced any cells! Check your Gmsh code.

Gmsh output:
Info    : Running 'gmsh cylinder.geo -2 -nopopup -format msh -o /tmp/tmpo_wp2_.msh' [Gmsh 2.8.3, 1 node, max. 8 threads]
Info    : Started on Wed Jun  1 17:33:45 2016
Info    : Reading 'cylinder.geo'...
Info    : Done reading 'cylinder.geo'
Info    : Meshing 1D...
Info    : Meshing curve 1 (Line)
Info    : Meshing curve 2 (Line)
Info    : Meshing curve 3 (Line)
Info    : Meshing curve 4 (Circle)
Info    : Meshing curve 5 (Circle)
Info    : Meshing curve 6 (Circle)
Info    : Meshing curve 7 (Circle)
Info    : Meshing curve 8 (Circle)
Info    : Meshing curve 9 (Circle)
Info    : Done meshing 1D (0 s)
Info    : Meshing 2D...
Info    : Meshing surface 11 (transfinite)
Info    : Meshing surface 13 (transfinite)
Info    : Meshing surface 15 (transfinite)
Info    : Done meshing 2D (0.00717998 s)
Info    : 2926 vertices 3121 elements
Info    : Writing '/tmp/tmpo_wp2_.msh'...
Info    : Done writing '/tmp/tmpo_wp2_.msh'
Info    : Stopped on Wed Jun  1 17:33:45 2016
"

**Comment by wd15** [comment]
@KDra, do you know which version of gmsh that you're using? I'm using,

    $ /home/wd15/anaconda/bin/gmsh --version
    2.11.0

which seems to work.

**Comment by KDra** [comment]
i went through a few versions. i think it was the latest one. i did something (i don't know what) though and it started working.

**Comment by wd15** [comment]
Closing this as the author has resolved the issue.
