### ISSUE TITLE
Tests fail to run on 3.1, 3.1.2

### ISSUE THREAD

**Issue by scbarton** [usnistgov/fipy#503]
I'm unable to run the test suite, on fipy 3.1 or 3.1.2. Here's the error trace:

```
scott$ python -c "import fipy; fipy.test()"
running egg_info
creating /var/folders/6g/304ssmh94nqfs4dnb0__1fsm0000gp/T/tmpnLQjcm/FiPy.egg-info
writing /var/folders/6g/304ssmh94nqfs4dnb0__1fsm0000gp/T/tmpnLQjcm/FiPy.egg-info/PKG-INFO
writing top-level names to /var/folders/6g/304ssmh94nqfs4dnb0__1fsm0000gp/T/tmpnLQjcm/FiPy.egg-info/top_level.txt
writing dependency_links to /var/folders/6g/304ssmh94nqfs4dnb0__1fsm0000gp/T/tmpnLQjcm/FiPy.egg-info/dependency_links.txt
writing manifest file '/var/folders/6g/304ssmh94nqfs4dnb0__1fsm0000gp/T/tmpnLQjcm/FiPy.egg-info/SOURCES.txt'
warning: manifest_maker: standard file '-c' not found

reading manifest file '/var/folders/6g/304ssmh94nqfs4dnb0__1fsm0000gp/T/tmpnLQjcm/FiPy.egg-info/SOURCES.txt'
writing manifest file '/var/folders/6g/304ssmh94nqfs4dnb0__1fsm0000gp/T/tmpnLQjcm/FiPy.egg-info/SOURCES.txt'
running test
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/fipy/__init__.py", line 164, in test
    cmdclass={'test': _TestClass(_test)})
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/usr/local/lib/python2.7/site-packages/fipy/tests/testClass.py", line 96, in finalize_options
    self.test_args.remove(self.distribution.test_suite)
ValueError: list.remove(x): x not in list
```

I've attempted this in Mac OS and Linux using python 2.7.

I just discovered fipy this week, and love it, so I'll be glad to help fix this issue. I decided to test because I was having trouble getting `matplotlib2DViewer` to work as expected.

**Comment by guyer** [comment]
Sorry I missed this until now. 

I've never seen this before. The message "warning: manifest_maker: standard file '-c' not found" actually leads me to believe there's something odd with the python interpreter, rather than FiPy.

Can you try going to the FiPy directory and running:
```
  python setup.py install
  python setup.py test
```

This should produce the same result as importing and running `fipy.test()`, but who knows.

**Comment by scbarton** [comment]
Using setup.py worked. It may be that the tests did not run originally because I used `pip install fipy` to install.
