### ISSUE TITLE
creation of meshes does not take distance units as input in dx

### ISSUE THREAD

**Issue by guyer** [usnistgov/fipy#553]
@achennu [reports](https://github.com/usnistgov/fipy/issues/#534#issuecomment-358469405) in #534:

The creation of meshes (1D in my case) does not seem to take distance units as its input in `dx`. That is `Grid1D(dx=PhysicalField(0.1, 'mm'), nx=100)` fails. Why is this so? Without the grid knowing its physical dimension, it seems that having source and diffusion terms with units is rendered futile. A possible workaround is to set the grid in SI units (but without a unit), and then convert all coefficients and terms to base units and 'implicitly' solve it in base units. That sort of works (hard to catch errors), but makes me wonder of the utility of having physical units in the library. Some notes of explanation would be appreciated.

In further progress, a simple `TransientTerm() == DiffusionTerm()` style equation, throws the error `arg 1 must be a 1-dimensional double array of appropriate size`. when I try to solve or sweep it. Solver is in PySparse, but other errors occur with other solvers. How can I debug this issue?

**Comment by achennu** [comment]
Hi @guyer , thanks for following up on the issue.

here is a simple example to demonstrate the problem:
```python
from __future__ import print_function, division
import fipy

print('Using fipy version: {}'.format(fipy.__version__))

from fipy import *

dx = PhysicalField(100, 'mum')
nx = 200

mesh = Grid1D(dx=dx, nx=nx)

# these lines give the same result

# from fipy.meshes.uniformGrid1D import UniformGrid1D
# 
# mesh = UniformGrid1D(dx=dx, nx=nx)
```

Running this on the latest fipy version (3.1.3.dev246+g654426c) results in:
```
Using fipy version: 3.1.3.dev246+g654426c
Traceback (most recent call last):
  File "grid_with_units.py", line 11, in <module>
    mesh = Grid1D(dx=dx, nx=nx)
  File "~/software/miniconda2/envs/fipy.dev/lib/python2.7/site-packages/fipy/meshes/factoryMeshes.py", line 190, in Grid1D
    return UniformGrid1D(dx=dx, nx=nx, overlap=overlap, communicator=communicator)
  File "~/software/miniconda2/envs/fipy.dev/lib/python2.7/site-packages/fipy/meshes/uniformGrid1D.py", line 107, in __init__
    self._setTopology()
  File "~/software/miniconda2/envs/fipy.dev/lib/python2.7/site-packages/fipy/meshes/uniformGrid1D.py", line 114, in _setTopology
    self._exteriorFaces = self.facesLeft | self.facesRight
  File "~/software/miniconda2/envs/fipy.dev/lib/python2.7/site-packages/fipy/meshes/abstractMesh.py", line 728, in facesLeft
    x = self.faceCenters[0]
  File "~/software/miniconda2/envs/fipy.dev/lib/python2.7/site-packages/fipy/meshes/abstractMesh.py", line 123, in faceCenters
    return FaceVariable(mesh=self, value=self._faceCenters,
  File "~/software/miniconda2/envs/fipy.dev/lib/python2.7/site-packages/fipy/meshes/uniformGrid1D.py", line 175, in _faceCenters
    return numerix.arange(self.numberOfFaces)[numerix.NewAxis, ...] * self.dx + self.origin
  File "~/software/miniconda2/envs/fipy.dev/lib/python2.7/site-packages/fipy/tools/dimensions/physicalField.py", line 336, in __add__
    return self._sum(other)
  File "~/software/miniconda2/envs/fipy.dev/lib/python2.7/site-packages/fipy/tools/dimensions/physicalField.py", line 318, in _sum
    raise TypeError, str(self) + ' and ' + str(other) + ' are incompatible.'
TypeError: [0] 1/mum and [[   0.  100.  200.  300.  400.  500.  600.  700.  800.  900. 1000. 1100.
  1200. 1300. 1400. 1500. 1600. 1700. 1800. 1900. 2000.]] are incompatible.

```

**Comment by achennu** [comment]
As pointed out from #558, the mesh not taking dx with units means that all equation term coefficients need to implicitly be in the spatial units of the mesh. The workaround I used is to apply `.inBaseUnits()` for all parameters while creating the equation terms. This was necessary for the source terms, as well as for the DiffusionTerm coefficients.


Essentially, there are two API points where fipy is suboptimal:

1) Mesh creation should consider spatial units
2) eqn.sweep (and .solve) don't accept PhysicalField time entities.

The latter I think could be solved easily in `sweep()` but accepting `dt` as PhysicalField and doing `float(dt.inUnitsOf('s').numericValue)`. The `inUnitsOf` is just to check that dt is in units of time, and not wrong units.

However, the creation of the mesh seems more complicated and I'm not sure I have a clear suggestion of required changes.

Overall, the presence of an elaborate PhysicalField infrastructure without a way to use them sensibly in the equations threw me for a bit.

**Comment by guyer** [comment]
Units used to work better (but never comprehensively), but nobody used them, so bitrot set in.

**Comment by achennu** [comment]
I'm surprised that nobody used them. They seem pretty useful to me. What do
you mean by "never comprehensively"? I can imagine that if they got in the
way of getting equations solved, then a user would drop units as a good
enough "workaround". I cast all to base units, which the is the same thing
I suppose.

Without the mesh being aware of it's dimensions, I suppose there is no way
units could work.

A pity about the bitrot. I'd say the documentation should already be
updated to clarify that units actually don't work in equations. It would
have saved me considerable time in debugging.

**Comment by guyer** [comment]
By "never comprehensively", I mean that they never survived going through solve, which limited their utility. 

Dimensional meshes used to work, and it's probably not too difficult to get them working again.

I have frequently used them more or less as you did, by combining dimensional parameters in to non-dimensional coefficients.
