### ISSUE TITLE
Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'

### ISSUE THREAD

**Issue by Kuan-Ying** [usnistgov/fipy#561]
Hi folks, 
My computer is Windows 10 x64 and the processor is also x64-based. 
When I tested the sample code on the website I got the following error.

<pre>Traceback (most recent call last):
  File "test.py", line 90, in <module>
    phaseEq.solve(phase, dt=dt)
  File "C:\Users\me\Miniconda3\envs\py2\lib\site-packages\fipy-unknown-py2.7.egg\fipy\terms\term.py", line 198, in solve
    solver = self._prepareLinearSystem(var, solver, boundaryConditions, dt)
  File "C:\Users\me\Miniconda3\envs\py2\lib\site-packages\fipy-unknown-py2.7.egg\fipy\terms\term.py", line 157, in _prepareLinearSystem
    buildExplicitIfOther=self._buildExplcitIfOther)
  File "C:\Users\me\Miniconda3\envs\py2\lib\site-packages\fipy-unknown-py2.7.egg\fipy\terms\binaryTerm.py", line 68, in _buildAndAddMatrices
    buildExplicitIfOther=buildExplicitIfOther)
  File "C:\Users\me\Miniconda3\envs\py2\lib\site-packages\fipy-unknown-py2.7.egg\fipy\terms\unaryTerm.py", line 99, in _buildAndAddMatrices
    diffusionGeomCoeff=diffusionGeomCoeff)
  File "C:\Users\me\Miniconda3\envs\py2\lib\site-packages\fipy-unknown-py2.7.egg\fipy\terms\cellTerm.py", line 163, in _buildMatrix
    self._buildMatrixNoInline_(L=L, oldArray=var.old, b=b, dt=dt, coeffVectors=coeffVectors)
  File "C:\Users\me\Miniconda3\envs\py2\lib\site-packages\fipy-unknown-py2.7.egg\fipy\terms\cellTerm.py", line 148, in _buildMatrixNoInline_
    L.addAt(coeffVectors['new value'].ravel() / dt, ids.ravel(), ids.swapaxes(0,1).ravel())
  File "C:\Users\me\Miniconda3\envs\py2\lib\site-packages\fipy-unknown-py2.7.egg\fipy\matrices\pysparseMatrix.py", line 246, in addAt
    self.matrix.update_add_at(vector, id1, id2)
TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'</pre>

This problem is similar to the problem mentioned in the link below.  
http://fipy.nist.narkive.com/fRBMPr5Q/problems-using-fipy-on-windows-7-computer
To resolve this problem, line 246 in pyparseMatrix.py has to be replaced by
`self.matrix.update_add_at(vector, id1.astype('int32'), id2.astype('int32'))`

**Comment by wd15** [comment]
@Kuan-Ying: did you resolve this issue? Does it work if you use the Scipy solvers, using "python test.py --scipy"?

**Comment by Kuan-Ying** [comment]
Yes, previously I resolve the problem by replaced line 246 in pyparseMatrix.py to 
`self.matrix.update_add_at(vector, id1.astype('int32'), id2.astype('int32'))`.
And your method also works without modifying pyparseMatrix.py, I can run my test.py if I use python "python test.py --scipy"
