### ISSUE TITLE
pip install does not work on empty env

### ISSUE THREAD

**Issue by achennu** [usnistgov/fipy#565]
The [recommended method](https://www.ctcms.nist.gov/fipy/INSTALLATION.html#recommended-method) of installing works ok, for fipy as the main installation target.

Essentially it creates a python environment that already contains numpy, so `pip install fipy` works. However, numpy seems to be a setup time dependency for fipy, but it is not explicitly stated and so installing to an empty environment fails.

To demonstrate:

```console
conda create -n tmp python=2.7
source activate tmp
```
Now if I try:
```console
pip install --no-cache-dir fipy
# same for pip install --no-cache-dir fipy numpy
Collecting fipy
  Downloading FiPy-3.1.3.tar.gz (5.6MB)
    100% |████████████████████████████████| 5.6MB 13.8MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-BzcLMs/fipy/setup.py", line 39, in <module>
        from fipy.tools.performance.efficiency_test import Efficiency_test
      File "fipy/__init__.py", line 45, in <module>
        from fipy.boundaryConditions import *
      File "fipy/boundaryConditions/__init__.py", line 2, in <module>
        from fipy.boundaryConditions.fixedFlux import *
      File "fipy/boundaryConditions/fixedFlux.py", line 38, in <module>
        from fipy.tools import numerix
      File "fipy/tools/__init__.py", line 85, in <module>
        serial, parallel = serialComm, parallelComm = _getComms()
      File "fipy/tools/__init__.py", line 77, in _getComms
        from fipy.tools.comms.dummyComm import DummyComm
      File "fipy/tools/comms/dummyComm.py", line 37, in <module>
        from fipy.tools import numerix
      File "fipy/tools/numerix.py", line 76, in <module>
        import numpy as NUMERIX
    ImportError: No module named numpy

```

Seems to be the case for the git repo install too still:

```console
pip install --no-cache-dir git+https://github.com/usnistgov/fipy#develop
Collecting git+https://github.com/usnistgov/fipy#develop
  Cloning https://github.com/usnistgov/fipy to /tmp/pip-Wh01Dc-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-Wh01Dc-build/setup.py", line 51, in <module>
        from fipy.tools.performance.efficiency_test import Efficiency_test
      File "fipy/__init__.py", line 45, in <module>
        from fipy.boundaryConditions import *
      File "fipy/boundaryConditions/__init__.py", line 2, in <module>
        from fipy.boundaryConditions.fixedFlux import *
      File "fipy/boundaryConditions/fixedFlux.py", line 51, in <module>
        from fipy.tools import numerix
      File "fipy/tools/__init__.py", line 96, in <module>
        serial, parallel = serialComm, parallelComm = _getComms()
      File "fipy/tools/__init__.py", line 88, in _getComms
        from fipy.tools.comms.dummyComm import DummyComm
      File "fipy/tools/comms/dummyComm.py", line 48, in <module>
        from fipy.tools import numerix
      File "fipy/tools/numerix.py", line 87, in <module>
        import numpy as NUMERIX
    ImportError: No module named numpy
```
Instead if I do:
```console
pip install --no-cache-dir numpy
Collecting numpy
  Downloading numpy-1.14.2-cp27-cp27mu-manylinux1_x86_64.whl (12.1MB)
    100% |████████████████████████████████| 12.1MB 12.9MB/s 
Installing collected packages: numpy
Successfully installed numpy-1.14.2

# then install fipy
pip install --no-cache-dir fipy 
Collecting fipy
  Downloading FiPy-3.1.3.tar.gz (5.6MB)
    100% |████████████████████████████████| 5.6MB 12.7MB/s 
Installing collected packages: fipy
  Running setup.py install for fipy ... done
Successfully installed fipy-3.1.3
```

It's not clear to me that numpy is listed as an install time requirement for fipy. But the problem seems to be the imports of fipy.tools which tries to cast numpy into numerix.

**Comment by guyer** [comment]
We'll consider adding a `requirements.txt` file, although I recall it being inadequate to the task the last time I checked.

Is there a reason you're not using `conda install`? (specifically, `conda install --channel guyer --channel conda-forge fipy nomkl`)

**Comment by achennu** [comment]
As I said, if fipy were the main install target then the conda install option works fine. 

But consider if fipy is to be listed as a dependency by another package. Then that package setup.py would look like:

```python
setup(
   name="FiPyNator",
   install_requires=['numpy', 'fipy'],
)
```

Since fipy's setup.py file does not use the setuptools ``setup`` function to specify that numpy is an install requirement for fipy, so ``pip install fipynator`` cannot resolve dependencies correctly, ensuring that numpy is available, and so ``fipy.tools.numerix`` linkages can be made.

Though the problem is more fundamental than that. Importing fipy's setup.py attempts to import the fipy package from source and perform manipulations, that lead to the error I indicated earlier. So, the build time run of fipy is not in line with the python packaging conventions.

Not sure if distributing wheels may be a way around it for the present.
