### ISSUE TITLE
Test error after install

### ISSUE THREAD

**Issue by oliverstefanov** [usnistgov/fipy#605]
Hello,
After a few unsuccessful attempts at installing on windows, I installed FiPy in a virtual box running Ubuntu 18. Running the install test, I get an "AttributeError: 'module' object has no attribute 'testFiPy'" (see full output below).

Running test.py gives me `Fgmsh: Relink '/home/steph/miniconda2/envs/FiPy-3.1.3/bin/../lib/./libgfortran.so.3' with '/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol 'clock_gettime'`

Running mesh20x20.py gives `QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.`

Is it a linking issue with Gmsh library ? Or gist library missing ? What should I do? Thanks!

Full install test output :
```bash
$ python setup.py test
running test
running egg_info
writing FiPy.egg-info/PKG-INFO
writing top-level names to FiPy.egg-info/top_level.txt
writing dependency_links to FiPy.egg-info/dependency_links.txt
writing entry points to FiPy.egg-info/entry_points.txt
reading manifest file 'FiPy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.png' found under directory 'examples'
warning: no previously-included files matching '*.pdf' found under directory 'examples'
warning: no previously-included files matching '*.png' found under directory 'fipy'
warning: no previously-included files matching '*.pdf' found under directory 'fipy'
warning: no files found matching '*.msh' under directory 'fipy'
writing manifest file 'FiPy.egg-info/SOURCES.txt'
running build_ext
fipy version 3.1.3
numpy version 1.14.6
pysparse version 1.3-dev
scipy version 1.1.0
matplotlib version 2.2.3
gist is not installed
mpi4py version 3.0.0
Trilinos version: 12.10.1
PyTrilinos version: 12.8
mayavi version 4.6.2
gmsh version gmsh: Relink `/home/steph/miniconda2/envs/FiPy-3.1.3/bin/../lib/./libgfortran.so.3' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
3.0.6
Traceback (most recent call last):
  File "setup.py", line 294, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules'
  File "/home/steph/miniconda2/envs/FiPy-3.1.3/lib/python2.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/home/steph/miniconda2/envs/FiPy-3.1.3/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/steph/miniconda2/envs/FiPy-3.1.3/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/steph/miniconda2/envs/FiPy-3.1.3/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/steph/miniconda2/envs/FiPy-3.1.3/lib/python2.7/site-packages/setuptools/command/test.py", line 228, in run
    self.run_tests()
  File "/home/steph/FiPy/FiPy-3.1.3/fipy/tests/testClass.py", line 236, in run_tests
    testLoader = loader_class()
  File "/home/steph/miniconda2/envs/FiPy-3.1.3/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/home/steph/miniconda2/envs/FiPy-3.1.3/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/home/steph/miniconda2/envs/FiPy-3.1.3/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/home/steph/miniconda2/envs/FiPy-3.1.3/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/steph/miniconda2/envs/FiPy-3.1.3/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'testFiPy'
```

*edited code tags*

**Comment by avaneeshnarla** [comment]
I am getting the same output when run on windows. I believe I have all of the packages, and can run many of the files, but the test fails with the same error as above.

**Comment by guyer** [comment]
Upgrading to the  [latest release v3.2](https://github.com/usnistgov/fipy/releases/tag/3.2) should resolve this
