### ISSUE TITLE
Tests failed after instalation

### ISSUE THREAD

**Issue by avaneeshnarla** [usnistgov/fipy#606]
Hi, I just installed FiPy, but I am getting several errors by running the test script in the examples folder. Is there a stable build that you would recommend? I am just trying to solve for viscous flows. The full output is below and attached in a notepad file ([test_log.txt](https://github.com/usnistgov/fipy/files/2470615/test_log.txt)).
```
> 
> ................................C:\Users\avane\Documents\FiPy-3.1.3\examples\diffusion\steadyState\mesh1D\inputPeriodic.py:1: StagnatedSolverWarning: The solver stagnated. Iterations: 48. Relative error: 2.20797e-10
>   #!/usr/bin/env python
> ....F.....................EE.....................C:\ProgramData\Miniconda2\lib\site-packages\fipy\variables\variable.py:1165: RuntimeWarning: divide by zero encountered in double_scalars
>   return self._BinaryOperatorVariable(lambda a,b: a/b, other)
> ........................................................................................F..........F........C:\Users\avane\Documents\FiPy-3.1.3\examples\reactiveWetting\liquidVapor1D.py:3: RuntimeWarning: divide by zero encountered in log
>   ##
> C:\Users\avane\Documents\FiPy-3.1.3\examples\reactiveWetting\liquidVapor1D.py:18: RuntimeWarning: divide by zero encountered in double_scalars
>   # of their official duties.  Pursuant to title 17 Section 105 of the
> .C:\Users\avane\Documents\FiPy-3.1.3\examples\reactiveWetting\liquidVapor2D.py:3: RuntimeWarning: divide by zero encountered in log
>   ##
> C:\Users\avane\Documents\FiPy-3.1.3\examples\reactiveWetting\liquidVapor2D.py:22: RuntimeWarning: divide by zero encountered in double_scalars
>   # other parties, and makes no guarantees, expressed or implied, about
> ...
> ======================================================================
> ERROR: import chemotaxis.input
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "C:\ProgramData\Miniconda2\lib\site-packages\fipy\tests\lateImportTest.py", line 53, in setUp
>     module = __import__(self.moduleName)
>   File "C:\Users\avane\Documents\FiPy-3.1.3\examples\chemotaxis\input.py", line 62, in <module>
>     from examples.chemotaxis.parameters import parameters
> ImportError: No module named examples.chemotaxis.parameters
> 
> ======================================================================
> ERROR: import chemotaxis.input2D
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "C:\ProgramData\Miniconda2\lib\site-packages\fipy\tests\lateImportTest.py", line 53, in setUp
>     module = __import__(self.moduleName)
>   File "C:\Users\avane\Documents\FiPy-3.1.3\examples\chemotaxis\input2D.py", line 62, in <module>
>     from examples.chemotaxis.parameters import parameters
> ImportError: No module named examples.chemotaxis.parameters
> 
> ======================================================================
> FAIL: grid3Dinput (diffusion.steadyState.otherMeshes)
> Doctest: diffusion.steadyState.otherMeshes.grid3Dinput
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "C:\ProgramData\Miniconda2\lib\doctest.py", line 2226, in runTest
>     raise self.failureException(self.format_failure(new.getvalue()))
> AssertionError: Failed doctest test for diffusion.steadyState.otherMeshes.grid3Dinput
>   File "C:\Users\avane\Documents\FiPy-3.1.3\examples\diffusion\steadyState\otherMeshes\grid3Dinput.py", line 6, in grid3Dinput
> 
> ----------------------------------------------------------------------
> File "C:\Users\avane\Documents\FiPy-3.1.3\examples\diffusion\steadyState\otherMeshes\grid3Dinput.py", line 10, in diffusion.steadyState.otherMeshes.grid3Dinput
> Failed example:
>     DiffusionTerm().solve(var)
> Exception raised:
>     Traceback (most recent call last):
>       File "C:\ProgramData\Miniconda2\lib\doctest.py", line 1315, in __run
>         compileflags, 1) in test.globs
>       File "<doctest diffusion.steadyState.otherMeshes.grid3Dinput[0]>", line 1, in <module>
>         DiffusionTerm().solve(var)
>       File "C:\ProgramData\Miniconda2\lib\site-packages\fipy\terms\term.py", line 211, in solve
>         solver = self._prepareLinearSystem(var, solver, boundaryConditions, dt)
>       File "C:\ProgramData\Miniconda2\lib\site-packages\fipy\terms\term.py", line 169, in _prepareLinearSystem
>         diffusionGeomCoeff=self._getDiffusionGeomCoeff(var),
>       File "C:\ProgramData\Miniconda2\lib\site-packages\fipy\terms\abstractDiffusionTerm.py", line 458, in _getDiffusionGeomCoeff
>         return self._getGeomCoeff(var)
>       File "C:\ProgramData\Miniconda2\lib\site-packages\fipy\terms\term.py", line 465, in _getGeomCoeff
>         self.geomCoeff = self._calcGeomCoeff(var)
>       File "C:\ProgramData\Miniconda2\lib\site-packages\fipy\terms\abstractDiffusionTerm.py", line 177, in _calcGeomCoeff
>         tmpBop = (coeff * FaceVariable(mesh=mesh, value=mesh._faceAreas) / mesh._cellDistances)[numerix.newaxis, :]
>       File "C:\ProgramData\Miniconda2\lib\site-packages\fipy\meshes\uniformGrid3D.py", line 248, in _cellDistances
>         XZdis[..., 0,...] = self.dy / 2.
>     IndexError: an index can only have a single ellipsis ('...')
> ----------------------------------------------------------------------
> File "C:\Users\avane\Documents\FiPy-3.1.3\examples\diffusion\steadyState\otherMeshes\grid3Dinput.py", line 15, in diffusion.steadyState.otherMeshes.grid3Dinput
> Failed example:
>     print numerix.allclose(a, c)
> Expected:
>     1
> Got:
>     False
> 
> 
> ======================================================================
> FAIL: TrenchMesh (levelSet.electroChem.trenchMesh)
> Doctest: levelSet.electroChem.trenchMesh.TrenchMesh
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "C:\ProgramData\Miniconda2\lib\doctest.py", line 2226, in runTest
>     raise self.failureException(self.format_failure(new.getvalue()))
> AssertionError: Failed doctest test for levelSet.electroChem.trenchMesh.TrenchMesh
>   File "C:\Users\avane\Documents\FiPy-3.1.3\examples\levelSet\electroChem\trenchMesh.py", line 44, in TrenchMesh
> 
> ----------------------------------------------------------------------
> File "C:\Users\avane\Documents\FiPy-3.1.3\examples\levelSet\electroChem\trenchMesh.py", line 63, in levelSet.electroChem.trenchMesh.TrenchMesh
> Failed example:
>     print mesh.globalNumberOfCells - len(numerix.nonzero(mesh.electrolyteMask)[0]) # doctest: +GMSH, +SERIAL
> Expected:
>     150
> Got:
>     160
> 
> 
> ======================================================================
> FAIL: mesh3D (cahnHilliard)
> Doctest: cahnHilliard.mesh3D
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "C:\ProgramData\Miniconda2\lib\doctest.py", line 2226, in runTest
>     raise self.failureException(self.format_failure(new.getvalue()))
> AssertionError: Failed doctest test for cahnHilliard.mesh3D
>   File "C:\Users\avane\Documents\FiPy-3.1.3\examples\cahnHilliard\mesh3D.py", line 6, in mesh3D
> 
> ----------------------------------------------------------------------
> File "C:\Users\avane\Documents\FiPy-3.1.3\examples\cahnHilliard\mesh3D.py", line 54, in cahnHilliard.mesh3D
> Failed example:
>     eq = (TransientTerm()
>           == DiffusionTerm(coeff=D * a**2 * (1 - 6 * PHI * (1 - PHI)))
>           - DiffusionTerm(coeff=(D, epsilon**2)))
> Exception raised:
>     Traceback (most recent call last):
>       File "C:\ProgramData\Miniconda2\lib\doctest.py", line 1315, in __run
>         compileflags, 1) in test.globs
>       File "<doctest cahnHilliard.mesh3D[8]>", line 2, in <module>
>         == DiffusionTerm(coeff=D * a**2 * (1 - 6 * PHI * (1 - PHI)))
>       File "C:\ProgramData\Miniconda2\lib\site-packages\fipy\variables\variable.py", line 1151, in __mul__
>         return self._BinaryOperatorVariable(lambda a,b: a*b, other)
>       File "C:\ProgramData\Miniconda2\lib\site-packages\fipy\variables\variable.py", line 1116, in _BinaryOperatorVariable
>         if not v.unit.isDimensionless() or len(v.shape) > 3:
>       File "C:\ProgramData\Miniconda2\lib\site-packages\fipy\variables\variable.py", line 255, in _getUnit
>         return self._extractUnit(self.value)
>       File "C:\ProgramData\Miniconda2\lib\site-packages\fipy\variables\variable.py", line 538, in _getValue
>         value = self._calcValue()
>       File "C:\ProgramData\Miniconda2\lib\site-packages\fipy\variables\cellToFaceVariable.py", line 48, in _calcValue
>         alpha = self.mesh._faceToCellDistanceRatio
>       File "C:\ProgramData\Miniconda2\lib\site-packages\fipy\meshes\uniformGrid3D.py", line 269, in _faceToCellDistanceRatio
>         XZdis[..., 0,...] = 1
>     IndexError: an index can only have a single ellipsis ('...')
> ----------------------------------------------------------------------
> File "C:\Users\avane\Documents\FiPy-3.1.3\examples\cahnHilliard\mesh3D.py", line 69, in cahnHilliard.mesh3D
> Failed example:
>     while elapsed < duration:
>         dt = min(100, numerix.exp(dexp))
>         elapsed += dt
>         dexp += 0.01
>         eq.solve(phi, dt=dt, solver=DefaultSolver(precon=None))
>         if __name__ == "__main__":
>             viewer.plot()
> Exception raised:
>     Traceback (most recent call last):
>       File "C:\ProgramData\Miniconda2\lib\doctest.py", line 1315, in __run
>         compileflags, 1) in test.globs
>       File "<doctest cahnHilliard.mesh3D[12]>", line 5, in <module>
>         eq.solve(phi, dt=dt, solver=DefaultSolver(precon=None))
>     NameError: name 'eq' is not defined
> 
> 
> ----------------------------------------------------------------------
> Ran 193 tests in 176.968s
> 
> FAILED (failures=3, errors=2)
```

**Comment by guyer** [comment]
The [current release v3.2](https://github.com/usnistgov/fipy/releases/tag/3.2) exhibits none of these behaviors for me
