### ISSUE TITLE
var.mesh: 'Property' object not callable...?

### ISSUE THREAD

**Issue by oliverstefanov** [usnistgov/fipy#608]
I'm trying to solve a Phase Field model but I keep getting the following error : 

Traceback (most recent call last):
  File "PF_model_G17.py", line 151, in <module>
    eq.solve(var=phase,dt=dt,solver=mysolver)
  File "/home/.../Programs/miniconda2/envs/fipy-3.1.3/lib/python2.7/site-packages/fipy/terms/term.py", line 211, in solve
    solver = self._prepareLinearSystem(var, solver, boundaryConditions, dt)
  File "/home/.../Programs/miniconda2/envs/fipy-3.1.3/lib/python2.7/site-packages/fipy/terms/term.py", line 170, in _prepareLinearSystem
    buildExplicitIfOther=self._buildExplcitIfOther)
  File "/home/.../Programs/miniconda2/envs/fipy-3.1.3/lib/python2.7/site-packages/fipy/terms/binaryTerm.py", line 57, in _buildAndAddMatrices
    **matrix = SparseMatrix(mesh=var.mesh)
TypeError: 'property' object is not callable**

I simplified my equations a great deal to see where it comes from but to no avail. I now have a single simple Phase Field Equation, which still gives me that error (phaseEq = TransientTerm(coeff= 1., var=phase) == DiffusionTerm(coeff= 1., var= phase))

My phase is defined as a CellVariable so I don't see what could be wrong, it should be able to call phase.mesh and there are no other variables in this simple equation...

Any hindsight would be very appreciated, thanks

**Comment by oliverstefanov** [comment]
Ok nevermind I had a problem elsewhere in my code

**Comment by guyer** [comment]
Glad you figured it out
