### ISSUE TITLE
Deprecate examples/levelSet/electroChem

### ISSUE THREAD

**Issue by guyer** [usnistgov/fipy#682]
@wd15 argues to get rid of these.

  - Nobody understands them but @wd15, and he doesn't use them
  - They have [problems with PETSc](https://app.circleci.com/jobs/github/usnistgov/fipy/1174) (#659)
  - They can't be run as plain examples, possibly due to futurizing?
     ```python
     Traceback (most recent call last):
       File "examples/levelSet/electroChem/gold.py", line 80, in <module>
         from .trenchMesh import TrenchMesh
     ValueError: Attempted relative import in non-package
     ```

**Comment by muratyesibolati** [comment]
I have a very similar problem. 
is this example not working?  thank you very much. 

 C:\Windows\System32\fipy>python examples/levelSet/electroChem/simpleTrenchSystem.py
Traceback (most recent call last):
  File "examples/levelSet/electroChem/simpleTrenchSystem.py", line 140, in <module>
    from .metalIonDiffusionEquation import buildMetalIonDiffusionEquation
ImportError: attempted relative import with no known parent package

**Comment by guyer** [comment]
It can be run as part of the test suite. It cannot be run by itself. It should be possible to copy the body into a plain Python script and run it after cleaning up the imports. For the reasons stated above, we are unlikely to do that.

**Comment by muratyesibolati** [comment]
@guyer  I see. I will give a try.  thank you for the info.
