### ISSUE TITLE
Input equations as a function type instead of `fipy.variables.binaryOperatorVariable.binOp` 

### ISSUE THREAD

**Issue by pavaninguva** [usnistgov/fipy#686]
Hi, I am trying to use an autodifferentiation tool to abstract away the need to evaluate the derivatives of certain functions for use as coefficients in the declaration of the equations subsequently. However, it seems that I am unable to do so since the following equations from this example: https://www.ctcms.nist.gov/fipy/examples/cahnHilliard/generated/examples.cahnHilliard.mesh2D.html
```
dfdphi = a**2 * phi * (1 - phi) * (1 - 2 * phi)
dfdphi_ = a**2 * (1 - phi) * (1 - 2 * phi)
d2fdphi2 = a**2 * (1 - 6 * phi * (1 - phi))
``` 
are of type  `<class 'fipy.variables.binaryOperatorVariable.binOp'>` and not a function as I naively expected. When I use the autodifferential tool `autograd.grad` as follows: 
```
def g(phi):
    return a**2 * phi**2 *(1.0-phi)**2
dfdphi = grad(g)
d2fdphi2 = grad(dfdphi)
```

The equations now are of type `function` and I get the following `TypeError`: 
```
TypeError: bad operand type for unary -: 'function
```
The full error trace is attached below: 

```
Traceback (most recent call last):
  File "test.py", line 45, in <module>
    eq.solve(dt=dt)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/terms/term.py", line 176, in solve
    solver = self._prepareLinearSystem(var, solver, boundaryConditions, dt)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/terms/term.py", line 130, in _prepareLinearSystem
    buildExplicitIfOther=self._buildExplcitIfOther)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/terms/coupledBinaryTerm.py", line 88, in _buildAndAddMatrices
    buildExplicitIfOther=buildExplicitIfOther)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/terms/binaryTerm.py", line 34, in _buildAndAddMatrices
    buildExplicitIfOther=buildExplicitIfOther)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/terms/binaryTerm.py", line 34, in _buildAndAddMatrices
    buildExplicitIfOther=buildExplicitIfOther)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/terms/binaryTerm.py", line 34, in _buildAndAddMatrices
    buildExplicitIfOther=buildExplicitIfOther)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/terms/binaryTerm.py", line 34, in _buildAndAddMatrices
    buildExplicitIfOther=buildExplicitIfOther)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/terms/unaryTerm.py", line 67, in _buildAndAddMatrices
    diffusionGeomCoeff=diffusionGeomCoeff)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/terms/cellTerm.py", line 126, in _buildMatrix
    coeffVectors = self._getCoeffVectors_(var=var, transientGeomCoeff=transientGeomCoeff, diffusionGeomCoeff=diffusionGeomCoeff)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/terms/cellTerm.py", line 86, in _getCoeffVectors_
    self._calcCoeffVectors_(var=var, transientGeomCoeff=transientGeomCoeff, diffusionGeomCoeff=diffusionGeomCoeff)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/terms/cellTerm.py", line 70, in _calcCoeffVectors_
    weight = self._getWeight(var, transientGeomCoeff, diffusionGeomCoeff)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/terms/implicitSourceTerm.py", line 44, in _getWeight
    combinedSign = numerix.array(diagonalSign)[..., numerix.newaxis] * numerix.sign(coeff)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/variables/variable.py", line 158, in __array__
    return numerix.array(self.value, t)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/variables/variable.py", line 493, in _getValue
    value = self._calcValue()
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/variables/operatorVariable.py", line 55, in _calcValue
    return self._calcValue_()
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/variables/binaryOperatorVariable.py", line 42, in _calcValue_
    val1 = self.var[1].value
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/variables/variable.py", line 493, in _getValue
    value = self._calcValue()
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/variables/operatorVariable.py", line 55, in _calcValue
    return self._calcValue_()
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/variables/unaryOperatorVariable.py", line 36, in _calcValue_
    return self.op(self.var[0].value)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/variables/variable.py", line 1153, in <lambda>
    return self._UnaryOperatorVariable(lambda a: -a)
TypeError: bad operand type for unary -: 'function'
```

Is it possible then to input the equations as functions or is such an approach unviable to start with. Thank you for your help!

**Comment by wd15** [comment]
I'm not sure how autograd works, but I get the impression that it isn't doing symbolic gradients. Well, at least I can't seem to extract a symbolic representation. It only seems to deal with types it understands. Probably best to use Sympy for this I think.
```
from sympy import diff, symbols
from sympy.utilities.lambdify import lambdify
from fipy import CellVariable, Grid1D

def diff_(f):
    """Takes a function and returns a raw diff of that function.
    """
    x = symbols('x')
    return lambdify(x, diff(f(x), x))

def f(x):
    return (1 - x) / (1 + x)

df = diff_(f)

mesh = Grid1D(nx=3)
var = CellVariable(mesh=mesh, value=0.0, name='x')

f_var = f(var)
df_var = df(var)

print(repr(f_var))
print(repr(df_var))
print(f_var.value)
print(df_var.value)
```
With Sympy you can create a raw Python function without Sympy objects. This allows you then to use FiPy objects instead. The above gives,
```
((1 - x) / (x + 1))
((-((1 - x)) / (pow((x + 1), 2))) - (1 / (x + 1)))
[1. 1. 1.]
[-2. -2. -2.]
```
