### ISSUE TITLE
Fipy is very slow when running a large simulation domain

### ISSUE THREAD

**Issue by pavaninguva** [usnistgov/fipy#694]
When I run a simulation with the following size: 
```
mesh = Grid2D(Lx=50.0, Ly=50.0, nx=50, ny=50)
```
The simulation starts in reasonable time and the trace starts appearing in my terminal. However, when keeping everything else the same, but I increase the domain size to: 
```
mesh = Grid2D(Lx=500.0, Ly=500.0, nx=250, ny=250)
```
It appears that it nothing is happening. The same problem occurs when I try to do an mpirun. Is there some pre-compiling or meshing step that blows up?

**Comment by guyer** [comment]
There is no pre-compiling and a `Grid2D` does not have very much overhead that depends on size. You're defining a problem with 25x more cells. Is the slowdown more than a factor of 25?

I can't speculate much more based solely on the mesh declaration. If you provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example), I can try to diagnose further.

**Comment by pavaninguva** [comment]
Ah! Yes! You are right regarding the overhead for the Grid2D. Apologies for that! However, I tried to use --inline flag to attempt a speedup, but I get the following error.  I am using the `mesh2DCoupled.py` as an MWE

This is the trace im getting
```
python mesh2DCoupled.py --inline
Traceback (most recent call last):
  File "mesh2DCoupled.py", line 180, in <module>
    exec(fipy.tests.doctestPlus._getScript())
  File "<string>", line 111, in <module>
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/terms/term.py", line 176, in solve
    solver = self._prepareLinearSystem(var, solver, boundaryConditions, dt)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/terms/term.py", line 130, in _prepareLinearSystem
    buildExplicitIfOther=self._buildExplcitIfOther)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/terms/coupledBinaryTerm.py", line 88, in _buildAndAddMatrices
    buildExplicitIfOther=buildExplicitIfOther)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/terms/binaryTerm.py", line 34, in _buildAndAddMatrices
    buildExplicitIfOther=buildExplicitIfOther)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/terms/unaryTerm.py", line 67, in _buildAndAddMatrices
    diffusionGeomCoeff=diffusionGeomCoeff)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/terms/cellTerm.py", line 131, in _buildMatrix
    self._buildMatrixInline_(L=L, oldArray=var.old, b=b, dt=dt, coeffVectors=coeffVectors)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/terms/cellTerm.py", line 110, in _buildMatrixInline_
    dt=dt)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/tools/inline.py", line 115, in _runInline
    extra_compile_args =['-O3'])
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/weave/inline_tools.py", line 356, in inline
    results = attempt_function_call(code,local_dict,global_dict)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/weave/inline_tools.py", line 425, in attempt_function_call
    function_list = function_catalog.get_functions(code,module_dir)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/weave/catalog.py", line 794, in get_functions
    function_list = self.get_cataloged_functions(code)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/weave/catalog.py", line 709, in get_cataloged_functions
    cat = get_catalog(path,mode)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/weave/catalog.py", line 480, in get_catalog
    sh = shelve.open(catalog_file,mode)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/weave/_dumb_shelve.py", line 51, in open
    return DbfilenameShelf(filename, flag)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/weave/_dumb_shelve.py", line 22, in __init__
    Shelf.__init__(self, _dumbdbm_patched.open(filename, flag))
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/weave/_dumbdbm_patched.py", line 164, in open
    return _Database(file)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/weave/_dumbdbm_patched.py", line 54, in __init__
    self._update()
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/weave/_dumbdbm_patched.py", line 68, in _update
    key, (pos, siz) = eval(line)
  File "<string>", line 1
    u'__path__\n\nint i,j;\nfor(i=0;i<ni;i++) {\n\tfor(j=0;j<nj;j++) {\n\t\t\n                int ID = j * ni + i;\n\n                faceCellIDs0[ID] = ID - ni;\n                faceCellIDs1[ID] = ID;\n\n                faceCellIDs0[ID + Nhor + j] = ID - 1;\n                faceCellIDs1[ID + Nhor + j] = ID;\n\n                if (j == 0) {\n                    faceCellIDs0[ID] = ID;\n                }\n\n                if (j == nj - 1) {\n                    faceCellIDs0[ID + ni] = ID;\n                    fau'__path__\n\nint i,j;\nfor(i=0;i<ni;i++) {\n\tfor(j=0;j<nj;j++) {\n\t\t\n                int ID = j * ni + i;\n\n                faceCellIDs0[ID] = ID - ni;\n                faceCellIDs1[ID] = ID;\n\n                faceCellIDs0[ID + Nhor + j] = ID - 1;\n                faceCellIDs1[ID + Nhor + j] = ID;\n\n                if (j == 0) {\n                    faceCellIDs0[ID] = ID;\n                }\n\n                if (j == nj - 1) {\n                    faceCellIDs0[ID + ni] = ID;\n                    faceCellIDs1[ID + ni] = ID;\n                }\n\n                if (i == 0) {\n                    faceCellIDs0[ID + Nhor + j] = ID;\n                }\n\n                if ( i == ni - 1 ) {\n                    faceCellIDs0[ID + Nhor + j + 1] = ID;\n                    faceCellIDs1[ID + Nhor + j + 1] = ID;\n                }\n\n            \n\t}\n}', (2560, 64)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^
SyntaxError: invalid syntax
```

Also to clarify, I can only do an MPI run using trillinos right? Thank you so much for your help!

**Comment by guyer** [comment]
`--inline` relies on the very stale [`weave`](https://github.com/scipy/weave) library and we no longer bother to test it. We should probably remove this option. Speedup was modest, anyway.

Parallel [support for PETSc](https://github.com/usnistgov/fipy/pull/659) should be released RealSoonNow[tm]. Performance is very similar to Trilinos.

**Comment by pavaninguva** [comment]
Hi! I have been working with the new PETSc implementation and I am able to run mpiruns and have done so with the test case : 
```
mpirun -np 3 python examples/parallel.py
```
I am able to reproduce the results in the documentation. 

However, when I try to do an mpirun for my code, it actually leads to a significant slow down. I uploaded an MWE of my code (slight modification of the https://www.ctcms.nist.gov/fipy/examples/cahnHilliard/generated/examples.cahnHilliard.mesh2DCoupled.html example) in the following public github repo: 

```
https://github.com/pavaninguva/fipy_mwe_CH
```

I would appeciate any help in getting any speed-ups of the calculations.

**Comment by guyer** [comment]
Slow down relative to what?
- PySparse in serial? This is a [known issue](https://www.ctcms.nist.gov/fipy/documentation/USAGE.html#solving-in-parallel). We'll be working on this in the near term.
- PETSc in serial? Don't use the LU solver. The GMRES solver that we use by default with PETSc performs considerably better than LU for this problem, particularly in parallel. Performance is actually on par with PySparse. Preconditioning would probably help even more.
