### ISSUE TITLE
importing mesh file created from pygmsh

### ISSUE THREAD

**Issue by KeunwooPark** [usnistgov/fipy#752]
Hi. I'm trying to create a mesh with pygmsh, and load it with fipy.
However, I faced an encoding error. 

I'm really new to mesh files. 

Here is my code.

```python
from fipy import *
from fipy import input
import pygmsh
import meshio
import numpy as np

nx = 300
ny = nx
dx = 0.05
dy = dx
L = nx*dx

# create mesh

geom = pygmsh.opencascade.Geometry(
    characteristic_length_min=dx,
    characteristic_length_max=dx)

volume = geom.add_rectangle([0, 0, 0], L, L)
cathode = geom.add_rectangle([20 * dx, L/3, 0], 5*dx, L/3)
anode = geom.add_rectangle([L-25*dx, L/3, 0], 5*dx, L/3)
result = geom.boolean_difference([volume], [cathode, anode])
mesh = pygmsh.generate_mesh(geom)

meshio.write("tmp.msh", mesh, file_format="gmsh22")
mesh = Gmsh2D("tmp.msh")
```

And this is the output.
```shell
Traceback (most recent call last):
  File "fipy_tutorial/thick_plate_capacitor_2d.py", line 29, in <module>
    mesh = Gmsh2D("tmp.msh")
  File "(erased)/python3.6/site-packages/fipy/meshes/gmshMesh.py", line 1601, in __init__
    background=background)
  File "(erased)/python3.6/site-packages/fipy/meshes/gmshMesh.py", line 161, in openMSHFile
    filetype = f.readline().strip()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 64: invalid continuation byte
```

I saw #586 , but there is no "gmsh-ascii" file format anymore.
Can someone explain what is going on? And any workarounds?

**Comment by KeunwooPark** [comment]
I found a workaround from this [issue](https://github.com/nschloe/pygmsh/issues/304).
Use ```geom.get_code()``` instead of saving a file.
```python
geom_string = geom.get_code()
mesh = Gmsh2D(geom_string)
```
