### ISSUE TITLE
Binder failed build

### ISSUE THREAD

**Issue by Davincb** [usnistgov/fipy#778]
Have this working otherwise on my local computer but thought this should be flagged for people looking to try it out:  

```bash
Installing pip dependencies: ...working... Ran pip subprocess with arguments:
['/srv/conda/envs/notebook/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/jovyan/binder/condaenv.8t9ly_pt.requirements.txt']
Pip subprocess output:
Obtaining file:///home/jovyan (from -r /home/jovyan/binder/condaenv.8t9ly_pt.requirements.txt (line 1))

failed
Pip subprocess error:
    ERROR: Command errored out with exit status 1:
     command: /srv/conda/envs/notebook/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/jovyan/setup.py'"'"'; __file__='"'"'/home/jovyan/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1ruc4qkp
         cwd: /home/jovyan/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jovyan/setup.py", line 15, in <module>
        from _setup.build_docs import build_docs
      File "/home/jovyan/_setup/build_docs.py", line 4, in <module>
        from future.utils import text_to_native_str
    ModuleNotFoundError: No module named 'future'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


CondaEnvException: Pip failed

orge/linux-64       2 MB

  Summary:

  Install: 114 packages
  Upgrade: 4 packages

  Total download: 576 MB

──────────────────────────────────────────────────────────────────────────────────────────────

time: 149.977
Removing intermediate container 9a6cee0b61e3
The command '/bin/sh -c TIMEFORMAT='time: %3R' bash -c 'time mamba env update -p ${NB_PYTHON_PREFIX} -f "binder/environment.yml" && time mamba clean --all -f -y && mamba list -p ${NB_PYTHON_PREFIX} '' returned a non-zero code: 1
```

**Comment by guyer** [comment]
Thanks for reporting!
