### ISSUE TITLE
How to convert exported OpenFOAM mesh file to gmsh -2 format “.msh2”

### ISSUE THREAD

**Issue by alisheikholeslam** [usnistgov/fipy#783]
Open source CFD software "OpenFOAM" can export a few mesh file types:
1) ansys fluent software ".msh"
2) Starmesh software ".vrt" for vertices, ".cel" for elements, and ".bnd" for boundary
3) ".VTK" format

I need to convert one of this types to gmsh format which can be used by FiPy library in python, '".msh2" format'.

I would be grateful if you could help me to solve this problem. 
[mesh.zip](https://github.com/usnistgov/fipy/files/6056803/mesh.zip)

---

I have used this library, but there were some problems.
when I try to open the ".msh" file, which is exported for fluent, below error was appeared:

As it is written in linke `https://pypi.org/project/meshio/1.8.9/` Ansys mesh can be read and converted by "meshio" but the error below is appeared:
```
mesh = meshio.read("OF_Cylinder.msh", file_format= "ansys-ascii")

ERROR: 
Traceback (most recent call last):
  File "C:/Users/Ali/Desktop/mesh change.py", line 5, in <module>
    mesh = meshio.read("OF_Cylinder.msh", file_format= "ansys-ascii")
  File "C:\Python27\lib\site-packages\meshio\helpers.py", line 176, in read
    return format_to_reader[file_format].read(filename)
  File "C:\Python27\lib\site-packages\meshio\ansys_io.py", line 318, in read
    key, data = _read_cells(f, line)
  File "C:\Python27\lib\site-packages\meshio\ansys_io.py", line 131, in _read_cells
    assert key != "mixed"
AssertionError
```
---

```
mesh = meshio.read("OF_Cylinder.msh")

ERROR=
Traceback (most recent call last):
  File "C:/Users/Ali/Desktop/mesh change.py", line 5, in <module>
    mesh = meshio.read("OF_Cylinder.msh")
  File "C:\Python27\lib\site-packages\meshio\helpers.py", line 176, in read
    return format_to_reader[file_format].read(filename)
  File "C:\Python27\lib\site-packages\meshio\msh_io\main.py", line 15, in read
    mesh = read_buffer(f)
  File "C:\Python27\lib\site-packages\meshio\msh_io\main.py", line 31, in read_buffer
    assert line == "$MeshFormat"
AssertionError
```
---

for Starmesh mesh type files, there are two seperated files for nodes and elements, that could not be converted directly.

---

".VTK" format has been read by meshio, but how to convert in to the -2 format one, directly

```
mesh = meshio.read("SandPro.vtk")
msh = meshio.write("mesh.msh", mesh, file_format="gmsh2-ascii")       worked
```
```
meshio-convert SandPro.vtk SandPro.msh                     didn't work

  File "C:/Users/Ali/Desktop/mesh change.py", line 12
    meshio-convert SandPro.vtk SandPro.msh
                         ^
SyntaxError: invalid syntax
```

**Comment by guyer** [comment]
This is for questions about FiPy. You need to ask this of the [meshio](https://github.com/nschloe/meshio) developers.
