### ISSUE TITLE
In python 3.9 __repr__ throws an exception with abs

### ISSUE THREAD

**Issue by benliddicott** [usnistgov/fipy#811]
In some circumstances, python __repr__ throws an exception.

Minimal reproduction:
```python
from fipy import *
from fipy import numerix as np
nx = 50
dx = 1. / float(nx)
mesh = Grid1D(nx=nx,dx=dx)
X = mesh.cellCenters[0]
phi = CellVariable(mesh=mesh, name="Solution")
eq = TransientTerm(coeff=1., var=phi) + ExponentialConvectionTerm(coeff=(1.,), var=phi) + abs((phi*phi))
print(f"{eq}")
```

Error is:
```
~/numpy-test/test1$ python test2.py 
Traceback (most recent call last):
  File "/home/ben/numpy-test/test1/test2.py", line 9, in <module>
    print(f"{eq}")
  File "/home/ben/miniconda3/envs/FiPy/lib/python3.9/site-packages/fipy/terms/binaryTerm.py", line 52, in __repr__
    return '(' + repr(self.term) + ' + ' + repr(self.other) + ')'
  File "/home/ben/miniconda3/envs/FiPy/lib/python3.9/site-packages/fipy/terms/explicitSourceTerm.py", line 31, in __repr__
    return repr(self.coeff)
  File "/home/ben/miniconda3/envs/FiPy/lib/python3.9/site-packages/fipy/variables/operatorVariable.py", line 255, in __repr__
    return self._getRepresentation()
  File "/home/ben/miniconda3/envs/FiPy/lib/python3.9/site-packages/fipy/variables/operatorVariable.py", line 93, in _getRepresentation
    return parseInstructions(instructions, style=style, argDict=argDict, id=id, freshen=freshen)
  File "/home/ben/miniconda3/envs/FiPy/lib/python3.9/site-packages/fipy/variables/operatorVariable.py", line 239, in _py3kInstructions
    raise SyntaxError("Unknown instruction: %s" % repr(ins))
SyntaxError: Unknown instruction: Instruction(opname='LOAD_METHOD', opcode=160, arg=1, argval='fabs', argrepr='fabs', offset=2, starts_line=None, is_jump_target=False)
```

Looks like adding these lines in `_OperatorVariableClass._py3kInstructions` fixes it:

```
                elif ins.opname == "LOAD_METHOD":
                    stack.append(ins.argval)
                elif ins.opname == "CALL_METHOD":
                    args, stack = stack[-ins.arg:], stack[:-ins.arg]
                    stack.append(stack.pop() + "(" + ", ".join(args) + ")")
```

Working by analogy with LOAD_GLOBAL and CALL_FUNCTION, However I don't know enough to know whether this is correct.

Probably _py2kInstructions will need a similar change.

**Comment by guyer** [comment]
Thanks for the report and the proposed fix. I don't think there's any need for parallel code in `_py2kInstructions`. This is due to new behavior in NumPy and Python 2.x is well beyond end of life.
