### ISSUE TITLE
IndexError: index n is out of bounds for axis 0 with size n using coupled equations

### ISSUE THREAD

**Issue by matanmus** [usnistgov/fipy#835]
Hi all, 

I am rather new to FiPy. I am trying to solve two coupled equations with a 2D mesh. When using only one of these equations (i.e., using either `eq = eq1` or `eq = eq2`) the calculation works fine. However,  when using the line `eq = eq1 & eq2` the following error message is obtained: `IndexError: index n is out of bounds for axis 0 with size n`, where n=nx*ny. I found a question posted last year with a [similar problem](https://github.com/usnistgov/fipy/issues/718). Unfortunately, the suggested solution (which was to include boundary conditions) does not work for me. Below please find the relevant parts of the code. I'll be happy to share the entire code in case it is relevant.

Thanks a lot in advance for any suggestion.

Matan

---
```
# Create a 2D solution mesh
nx = ny = 50
dx = dy = 0.1
mesh = Grid2D(nx=nx, ny=ny, dx=dx, dy=dy)

# Create variables
phi = CellVariable(name=r"$\phi$", mesh=mesh, value=-1.)
sigma = CellVariable(name=r"$\sigma", mesh=mesh, value=0.01) 

# Boundary Conditions
phi_bc = -1
phi.constrain(phi_bc, mesh.facesLeft)
phi.constrain(phi_bc, mesh.facesRight)
phi.constrain(phi_bc, mesh.facesUp)
phi.constrain(phi_bc, mesh.facesDown)

sigma_bc = 0.01
sigma.constrain(sigma_bc, mesh.facesLeft)
sigma.constrain(sigma_bc, mesh.facesRight)
sigma.constrain(sigma_bc, mesh.facesUp)
sigma.constrain(sigma_bc, mesh.facesDown)

# Model Parameters
r0 = 5 #radius
kappa = 0.1
epsilon = 2*dx
normKappa = 3*kappa/(4*numerix.sqrt(2)*epsilon**3)
a0 = 2*numerix.pi*r0

# Expressions for Model Equations
diffTerm1 = DiffusionTerm(coeff=(2*normKappa*epsilon**2, 3*phi**2 - 1), var=phi)
diffTerm2 = DiffusionTerm(coeff=(2*normKappa*epsilon**2, epsilon**2, 1.), var=phi)
sourceTerm1 = ImplicitSourceTerm(coeff=2*normKappa*(3*phi**2)*phi**2, var=phi)
sourceTerm2 = ImplicitSourceTerm(coeff=2*normKappa*(3*phi**2), var=phi)
diffTerm3 = DiffusionTerm(coeff=(2*epsilon**2, sigma), var=phi)

# Equations
eq1 = (TransientTerm(var=phi) == -diffTerm1 + diffTerm2 + sourceTerm1 - sourceTerm2 - diffTerm3)
eq2 = (TransientTerm(var=sigma) == phi.grad.dot(phi.grad)/2 - numerix.sqrt(2)*a0/(3*epsilon))

eq = eq1 & eq2
```

**Comment by matanmus** [comment]
Hi guyer,

Thank you for your quick reply. I am also using Python 3.9.5, which runs on an M1 MacBook. Here is the traceback I get using `nx = ny = 21:`
```
Traceback (most recent call last):
  File "/Users/matanmussel/Dropbox/Research/UniHaifa/Dynamic pearling/Fipy/PFapproxHelfrich/CampHern2006_2D-2.py", line 97, in <module>
    eq.solve(dt=dt)
  File "/Users/matanmussel/opt/miniconda3/envs/fipy/lib/python3.9/site-packages/fipy/terms/term.py", line 176, in solve
    solver = self._prepareLinearSystem(var, solver, boundaryConditions, dt)
  File "/Users/matanmussel/opt/miniconda3/envs/fipy/lib/python3.9/site-packages/fipy/terms/term.py", line 124, in _prepareLinearSystem
    var, matrix, RHSvector = self._buildAndAddMatrices(var,
  File "/Users/matanmussel/opt/miniconda3/envs/fipy/lib/python3.9/site-packages/fipy/terms/coupledBinaryTerm.py", line 82, in _buildAndAddMatrices
    tmpVar, tmpMatrix, tmpRHSvector = uncoupledTerm._buildAndAddMatrices(tmpVar,
  File "/Users/matanmussel/opt/miniconda3/envs/fipy/lib/python3.9/site-packages/fipy/terms/binaryTerm.py", line 28, in _buildAndAddMatrices
    tmpVar, tmpMatrix, tmpRHSvector = term._buildAndAddMatrices(var,
  File "/Users/matanmussel/opt/miniconda3/envs/fipy/lib/python3.9/site-packages/fipy/terms/unaryTerm.py", line 62, in _buildAndAddMatrices
    var, matrix, RHSvector = self._buildMatrix(var,
  File "/Users/matanmussel/opt/miniconda3/envs/fipy/lib/python3.9/site-packages/fipy/terms/abstractDiffusionTerm.py", line 287, in _buildMatrix
    var, L, b = self.__higherOrderbuildMatrix(var, SparseMatrix, boundaryConditions=boundaryConditions, dt=dt, transientGeomCoeff=transientGeomCoeff, diffusionGeomCoeff=diffusionGeomCoeff)
  File "/Users/matanmussel/opt/miniconda3/envs/fipy/lib/python3.9/site-packages/fipy/terms/abstractDiffusionTerm.py", line 376, in __higherOrderbuildMatrix
    b = numerix.asarray(L * lowerOrderb) + b
  File "/Users/matanmussel/opt/miniconda3/envs/fipy/lib/python3.9/site-packages/fipy/matrices/petscMatrix.py", line 726, in __mul__
    x = other[self._localNonOverlappingColIDs]
IndexError: index 441 is out of bounds for axis 0 with size 441
```

**Comment by guyer** [comment]
OK. Please provide the literal code that you are running. At a minimum, there's an import missing, but based on your edit history, I suspect the example you posted above is not your actual code?

**Comment by matanmus** [comment]
Hi guyer, 

Here is the full code I am using. Note that `CircleInArray` is a function I wrote for defining the initial condition of `phi`. 

Thanks again,
Matan

```
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import os
from fipy import CellVariable, Grid2D, GaussianNoiseVariable, DiffusionTerm, TransientTerm, ImplicitSourceTerm, Viewer
from fipy.tools import numerix
import time
from CircleInArray import CircleInArray

def findMinMaxVals(phi, psi, MinMaxVec):
    maxPhi = MinMaxVec[0]
    minPhi = MinMaxVec[1]
    maxPsi = MinMaxVec[2]
    minPsi = MinMaxVec[3]
    maxPhi = max(max(phi), maxPhi)
    minPhi = min(min(phi), minPhi)
    maxPsi = max(max(psi), maxPsi)
    minPsi = min(min(psi), minPsi)
    return [maxPhi, minPhi, maxPsi, minPsi]

start_time = time.time()

# create a 2D solution mesh
nx = ny = 50
dx = dy = 0.1
mesh = Grid2D(nx=nx, ny=ny, dx=dx, dy=dy)

# create variables
phi = CellVariable(name=r"$\phi$", mesh=mesh, value=-1.) # hasOld=True,
sigma = CellVariable(name=r"$\sigma", mesh=mesh, value=0.01) #hasOld=True

#Boundary conditions --- I am not sure if this is the correct way to include these
phi_bc = -1
phi.constrain(phi_bc, mesh.facesLeft)
phi.constrain(phi_bc, mesh.facesRight)
phi.constrain(phi_bc, mesh.facesUp)
phi.constrain(phi_bc, mesh.facesDown)

sigma_bc = 0.01
sigma.constrain(sigma_bc, mesh.facesLeft)
sigma.constrain(sigma_bc, mesh.facesRight)
sigma.constrain(sigma_bc, mesh.facesUp)
sigma.constrain(sigma_bc, mesh.facesDown)

# Initial phi
r0 = 5 #radius
x0 = 20 #position of center of circle
y0 = 20
initCond = CircleInArray(nx, ny, x0, y0, r0)
phi[:] = initCond.reshape((nx*ny))

# Model Parameters
r0 = 5 #radius
kappa = 0.1
epsilon = 2*dx
normKappa = 3*kappa/(4*numerix.sqrt(2)*epsilon**3)
a0 = 2*numerix.pi*r0
V0 = numerix.pi*r0**2

diffTerm1 = DiffusionTerm(coeff=(2*normKappa*epsilon**2, 3*phi**2 - 1), var=phi)
diffTerm2 = DiffusionTerm(coeff=(2*normKappa*epsilon**2, epsilon**2, 1.), var=phi)
sourceTerm1 = ImplicitSourceTerm(coeff=2*normKappa*(3*phi**2)*phi**2, var=phi)
sourceTerm2 = ImplicitSourceTerm(coeff=2*normKappa*(3*phi**2), var=phi)
diffTerm3 = DiffusionTerm(coeff=(2*epsilon**2, sigma), var=phi)

# Equations
eq1 = (TransientTerm(var=phi) == -diffTerm1 + diffTerm2 + sourceTerm1 - sourceTerm2 - diffTerm3)
eq2 = (TransientTerm(var=sigma) == phi.grad.dot(phi.grad)/2 - numerix.sqrt(2)*a0/(3*epsilon))

eq = eq1 & eq2

# We use exponentially increasing time steps to keep the simulation “interesting”.
dexp = -5
elapsed = 0.
duration = 0.06

# Prepare x,y axis
x = np.arange(0, nx*dx, dx)
y = np.arange(0, ny*dy, dy)
X, Y = np.meshgrid(x, y)

maxPhi = 0.
minPhi = 1.
maxPsi = 0.
minPsi = 1.
phiList = []
psiList = []
timeList = []
dtList = []
# solving the equation
while elapsed < duration:
    dt = min(100, numerix.exp(dexp))
    elapsed += dt
    dexp += 0.01
    eq.solve(dt=dt)
    if max(phi)>1:
        print('t = ', elapsed, ', max(phi) = ', max(phi))

    phiList.append(np.array(phi))
    timeList.append(elapsed)
    dtList.append(dt)

    [maxPhi, minPhi, maxPsi, minPsi] = findMinMaxVals(phi, phi, [maxPhi, minPhi, maxPsi, minPsi])

print('t = ', elapsed, ', [phi] = [', minPhi, ', ', maxPhi, '], [psi] = [', minPsi, ', ', maxPsi, ']')
print('---')
print(timeList)
np.savez('data.npz', phiList=phiList, psiList=psiList, timeList=timeList, dtList=dtList, nx=nx, ny=ny, MinMaxVec = [maxPhi, minPhi, maxPsi, minPsi], X=X, Y=Y)
print('data saved')

print("--- %.4s seconds ---" % (time.time() - start_time))
```

**Comment by guyer** [comment]
> Note that `CircleInArray` is a function I wrote for defining the initial condition of `phi`.

Please provide [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)!

If I can't run your code, I can't troubleshoot it.

**Comment by matanmus** [comment]
Oh, I apologize again. Here is a minimal reproducible example. For 'eq = eq1 & eq2' I get the above-mentioned error message while for 'eq = eq1' it works just fine.

```
from fipy import CellVariable, Grid2D, GaussianNoiseVariable, DiffusionTerm, TransientTerm, ImplicitSourceTerm, Viewer
from fipy.tools import numerix

# create a 2D solution mesh
nx = ny = 50
dx = dy = 0.1
mesh = Grid2D(nx=nx, ny=ny, dx=dx, dy=dy)

# create variables
phi = CellVariable(name=r"$\phi$", mesh=mesh, value=-1.) 
sigma = CellVariable(name=r"$\sigma", mesh=mesh, value=0.01) 

# Boundary conditions
phi_bc = -1
phi.constrain(phi_bc, mesh.facesLeft)
phi.constrain(phi_bc, mesh.facesRight)
phi.constrain(phi_bc, mesh.facesUp)
phi.constrain(phi_bc, mesh.facesDown)

sigma_bc = 0.01
sigma.constrain(sigma_bc, mesh.facesLeft)
sigma.constrain(sigma_bc, mesh.facesRight)
sigma.constrain(sigma_bc, mesh.facesUp)
sigma.constrain(sigma_bc, mesh.facesDown)

# Equations
diffTerm = DiffusionTerm(coeff=(1., 3*phi**2 - 1), var=phi)
sourceTerm = ImplicitSourceTerm(coeff=(3*phi**2)*phi**2, var=phi)

eq1 = (TransientTerm(var=phi) == -diffTerm + sourceTerm)
eq2 = (TransientTerm(var=sigma) == phi.grad.dot(phi.grad)/2 - numerix.sqrt(2))

eq = eq1 & eq2

# We use exponentially increasing time steps to keep the simulation “interesting”.
dexp = -5
elapsed = 0.
duration = 0.06

# solving the equation
while elapsed < duration:
    dt = min(100, numerix.exp(dexp))
    elapsed += dt
    dexp += 0.01
    eq.solve(dt=dt)
```

**Comment by guyer** [comment]
I can't find that we've documented this anywhere (see #836), but higher-order `DiffusionTerm`s are not compatible with coupled equations. I don't know why your first example worked for me.

As it stands, your equations aren't really coupled anyway. `eq1` only has terms implicit in `phi` and `eq2` only has terms implicit in `sigma`. You can solve them separately without losing anything at all.

Alternatively, you could couple them by separating `eq1` into two 2nd order equations.

**Comment by matanmus** [comment]
Hi guyer,

Thank you very much for your answer, which is very helpful. In this case, where the two equations aren't very coupled, may I use the following ?
```
eq1 = ...
eq2 = ...
eq1.solve(dt=dt)
eq2.solve(dt=dt)
```

**Comment by guyer** [comment]
No activity in ~4 months
