### ISSUE TITLE
Negation of ResidualTerm throws error

### ISSUE THREAD

**Issue by Maxwellfire** [usnistgov/fipy#885]
Background: I am trying to implement newton iterations, as described in [here](https://gist.github.com/guyer/f29c759fd7f0f01363b8483c7bc644cb). In this document, they use a `fipy.ResidualTerm` to avoid having to recalculate the entire simple equation as an explicit source term

The issue:
Residual terms don't seem to implement coefficients, and so are not able to be negated. A simple piece of code demonstrates the problem: 
```
import fipy
-fipy.ResidualTerm(equation=None)
```
which throws the error:
```
Traceback (most recent call last):

  File "/tmp/ipykernel_36715/862288887.py", line 1, in <cell line: 1>
    -fipy.ResidualTerm(equation=None)

  File "/home/max/Tools/anaconda3/envs/fipy/lib/python3.9/site-packages/fipy/terms/nonDiffusionTerm.py", line 23, in __neg__
    return self.__class__(coeff=-self.coeff, var=self.var)

TypeError: __init__() got an unexpected keyword argument 'coeff'
```

Looking at the code, this seems to happen because the signature of the Residual term is different from every other term. Every other term is fully defined by a coefficient and a variable, but `ResidualTerm` is defined by an equation.

**Comment by Maxwellfire** [comment]
I'm a bit confused why this was closed as invalid? Are you saying that ResidualTerms should not be able to be negated by design? 

The bug I was pointing out is a mismatch between how the super class `nonDiffusionTerm` expects the constructor of all subclasses to be, and how `ResidualTerm` is actually constructed.

In my own code I am use the proper constructor with an equation, but since negation tries to construct a new Object with a wrong constructor, it fails

**Comment by guyer** [comment]
It was closed because `ResidualTerm(equation=None)` doesn't make any sense. That you say negation doesn't work when you supply an equation merits investigation.

Your bug report (and your followup) seemed fixated on the constructor being different. Yes, the constructor is different, because the nature of the term is different.

**Comment by Maxwellfire** [comment]
The reason that I wrote `None` for the equation is that it didn't seem relevant what the particular equation was. That's not what the bug is about.

Here's a piece of code that uses a proper equation that fails in the same way
```
import fipy
mesh = fipy.Grid1D(nx=100, dx=1)
var1 = fipy.CellVariable(mesh=mesh, hasOld=True, value = 1.0)
var2 = fipy.CellVariable(mesh=mesh, hasOld=True, value = 1.0)
eq1 = fipy.TransientTerm(var = var1, coeff = 1.) == fipy.DiffusionTerm(var = var1, coeff=1.)
eq2 = fipy.TransientTerm(var = var2, coeff = 1.) == fipy.DiffusionTerm(var = var2, coeff=1.) + fipy.ResidualTerm(equation=eq1)
```

As I said in my previous comment, the problem is not that I'm calling a constructor in a different way. The problem is that `fipy.ResidualTerm` found in `fipy/terms/residualTerm.py` is a subclass of `_ExplicitSourceTerm` which is a subclass of `SourceTerm` which is a subclass of `CellTerm`, which is a subclass of `_NonDiffusionTerm`. 

`_NonDiffusionTerm` has the following method defined in `/fipy/terms/nonDiffusionTerm.py`:
```
class _NonDiffusionTerm(_UnaryTerm):

    def __neg__(self):
        r"""
         Negate a `Term`.

           >>> -__NonDiffusionTerm(coeff=1.)
           __NonDiffusionTerm(coeff=-1.0)

        """
        if isinstance(self.coeff, (tuple, list)):
            return self.__class__(coeff=-numerix.array(self.coeff), var=self.var)
        else:
            return self.__class__(coeff=-self.coeff, var=self.var)
```

This `__neg__` method assumes that the constructor of all subclasses has the form `__class__(coeff=-self.coeff, var=self.var)` which is not true for the `ResidualTerm` subclass. The solution could be to overload the `__neg__` operator for this subclass.

**Comment by guyer** [comment]
I see the problem and will fix it. In the interim, this problem can be avoided by changing
```python
eq2 = fipy.TransientTerm(var = var2, coeff = 1.) == fipy.DiffusionTerm(var = var2, coeff=1.) + fipy.ResidualTerm(equation=eq1)
```
to
```python
eq2 = (fipy.TransientTerm(var = var2, coeff = 1.) == fipy.DiffusionTerm(var = var2, coeff=1.)) + fipy.ResidualTerm(equation=eq1)
```

This works because, internally, FiPy converts
```python
fipy.TransientTerm(var = var2, coeff = 1.) == fipy.DiffusionTerm(var = var2, coeff=1.)
```
to
```python
fipy.TransientTerm(var = var2, coeff = 1.) - fipy.DiffusionTerm(var = var2, coeff=1.)
```
(`== 0` is implicit) and then
```python
(fipy.TransientTerm(var = var2, coeff = 1.) - fipy.DiffusionTerm(var = var2, coeff=1.)) + fipy.ResidualTerm(equation=eq1)
```
to
```python
fipy.TransientTerm(var = var2, coeff = 1.) - fipy.DiffusionTerm(var = var2, coeff=1.) + fipy.ResidualTerm(equation=eq1)
```
avoiding the faulty negation.
