### ISSUE TITLE
Having problem with Viewer

### ISSUE THREAD

**Issue by guyer** [usnistgov/fipy#944]
### Discussed in https://github.com/usnistgov/fipy/discussions/943

<div type='discussions-op-text'>

<sup>Originally posted by **RadheChandu** August 29, 2023</sup>
Hello FipyTeam,

I am getting the following error while I was trying the examples on FiPy website. 

```python
Uncaught exception:
Traceback (most recent call last):
  File "~\test1.py", line 30, in <module>
    viewer = Viewer(vars=phi,
  File "C:\ProgramData\Anaconda3\lib\site-packages\fipy\viewers\__init__.py", line 105, in Viewer
    for name, ep in sorted(enpts):
TypeError: '<' not supported between instances of 'EntryPoint' and 'EntryPoint'
```

This was the example code I was working on.

```python
from fipy import Grid1D, ExplicitDiffusionTerm, TransientTerm, Viewer, CellVariable

nx = 50
dx = 1.
mesh = Grid1D(nx=nx, dx=dx)

phi = CellVariable(name="solution variable",
                   mesh=mesh,
                   value=0.)

D = 1.

valueLeft = 1
valueRight = 0

phi.constrain(valueRight, mesh.facesRight)
phi.constrain(valueLeft, mesh.facesLeft)

eqX = TransientTerm() == ExplicitDiffusionTerm(coeff=D)


if __name__ == '__main__':
    viewer = Viewer(vars=phi,
                    datamin=0., datamax=1.)
    viewer.plot()
```

I have even tried installing on a new environment, but still was getting the same error.

Can someone please help me solve this error?</div>

**Comment by guyer** [comment]
[`pkg_resources`](https://setuptools.pypa.io/en/latest/pkg_resources.html) is deprecated. Update to use [`importlib.metadata`](https://docs.python.org/3/library/importlib.metadata.html).
