### ISSUE TITLE
PETSc 3.20.0 broke the world

### ISSUE THREAD

**Issue by guyer** [usnistgov/fipy#963]
Breakages with PETSc observed in #946 correspond to [PETSc 3.20.0](https://dev.azure.com/guyer/FiPy/_build/results?buildId=844&view=logs&j=6e9fd3b2-3876-5f92-ebcc-0273b412dd37&t=9e30d64e-08f3-56bc-e828-0c4d9a37260a&l=220), (released [2023-09-28](https://petsc.org/release/changes/), conda-forge [petsc4py feedstock updated 2023-10-04](https://github.com/conda-forge/petsc4py-feedstock/commits/main)). Previous [PETSc 3.18.4](https://dev.azure.com/guyer/FiPy/_build/results?buildId=838&view=logs&j=d140db5a-ea74-5114-89c8-047f038a6232&t=e01c99fe-a45f-5995-24fb-d520d2bba4ff&l=213) worked fine.

- [ ] Assembly error
    ```python
    Exception raised:
        Traceback (most recent call last):
          File "/Users/guyer/mambaforge-arm/envs/petsc4py319/lib/python3.11/doctest.py", line 1351, in __run
            exec(compile(example.source, filename, "single",
          File "<doctest fipy.matrices.petscMatrix._PETScMatrix.__mul__[10]>", line 1, in <module>
            numerix.allclose(numerix.array((1,2,3),'d') * L1, tmp)
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
          File "/Users/guyer/Documents/research/FiPy/fipy/fipy/matrices/petscMatrix.py", line 168, in __rmul__
            self.matrix.multTranspose(x, y)
          File "petsc4py/PETSc/Mat.pyx", line 1356, in petsc4py.PETSc.Mat.multTranspose
        petsc4py.PETSc.Error: error code 73
        [0] MatMultTranspose() at /Users/runner/miniforge3/conda-bld/petsc_1695965956423/work/src/mat/interface/matrix.c:2637
        [0] Object is in wrong state
        [0] Not for unassembled vector, did you call VecAssemblyBegin()/VecAssemblyEnd()?
    ```
- [ ] Really slow
    Comparison of the runtimes for FiPy's test suite vs petsc4py version (these are only the 40 slowest tests when using petsc4py 3.20.1):
    ![Comparison of runtimes vs petsc4py version for 40 slowest test runtimes with petsc4py 3.20.1](https://github.com/usnistgov/fipy/assets/1830725/02d34cf0-dc71-436b-9155-f75753a5ad14)

    Ratio of runtimes for FiPy's test suite between petsc4py versions
    ![Ratio of runtimes for FiPy's test suite between petsc4py versions](https://github.com/usnistgov/fipy/assets/1830725/703060bf-bdd8-4f6a-b977-24499a8bd45d)

**Comment by guyer** [comment]
[Mat.setValuesCSR()](https://github.com/petsc/petsc/blob/c373386401c23a900b8d8448dc0b1bd4ba1cb6ca/src/binding/petsc4py/src/petsc4py/PETSc/Mat.pyx#L2576) got astronomically slower. Compare petsc4py 3.18.4:
```
Total time: 0.154681 s
File: /Users/guyer/Documents/research/FiPy/fipy/fipy/matrices/petscMatrix.py
Function: addAt at line 284

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   284                                               @profile
   285                                               def addAt(self, vector, id1, id2):
   286                                                   """
   287                                                   Add elements of `vector` to the positions in the matrix corresponding to (`id1`,`id2`)
   288                                           
   289                                                       >>> L = _PETScMatrixFromShape(rows=3, cols=3, bandwidth=3)
   290                                                       >>> L.put([3.,10.,numerix.pi,2.5], [0,0,1,2], [2,1,1,0])
   291                                                       >>> L.addAt([1.73,2.2,8.4,3.9,1.23], [1,2,0,0,1], [2,2,0,0,2])
   292                                                       >>> print(L)
   293                                                       12.300000  10.000000   3.000000  
   294                                                           ---     3.141593   2.960000  
   295                                                        2.500000      ---     2.200000  
   296                                                   """
   297        33        348.0     10.5      0.2          self.matrix.assemble(self.matrix.AssemblyType.FLUSH)
   298        66     154330.0   2338.3     99.8          self.matrix.setValuesCSR(*self._ijv2csr(id2, id1, vector),
   299        33          3.0      0.1      0.0                                   addv=True)
```
to petsc4py 3.20.1
```
Total time: 82.0462 s
File: /Users/guyer/Documents/research/FiPy/fipy/fipy/matrices/petscMatrix.py
Function: addAt at line 284

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   284                                               @profile
   285                                               def addAt(self, vector, id1, id2):
   286                                                   """
   287                                                   Add elements of `vector` to the positions in the matrix corresponding to (`id1`,`id2`)
   288                                           
   289                                                       >>> L = _PETScMatrixFromShape(rows=3, cols=3, bandwidth=3)
   290                                                       >>> L.put([3.,10.,numerix.pi,2.5], [0,0,1,2], [2,1,1,0])
   291                                                       >>> L.addAt([1.73,2.2,8.4,3.9,1.23], [1,2,0,0,1], [2,2,0,0,2])
   292                                                       >>> print(L)
   293                                                       12.300000  10.000000   3.000000  
   294                                                           ---     3.141593   2.960000  
   295                                                        2.500000      ---     2.200000  
   296                                                   """
   297        33       3853.0    116.8      0.0          self.matrix.assemble(self.matrix.AssemblyType.FLUSH)
   298        66   82042326.0    1e+06    100.0          self.matrix.setValuesCSR(*self._ijv2csr(id2, id1, vector),
   299        33          3.0      0.1      0.0                                   addv=True)
```

(`self._ijv2csr()` did not change)

**Comment by guyer** [comment]
["`MatSetValues()` and friends will now provide reasonable performance when no preallocation information is provided" in PETSc 3.19](https://petsc.org/release/changes/319/) is probably the culprit.

**Comment by guyer** [comment]
PETSc matrix preallocation has been commented out since the suite was added to FiPy

- Uncommenting [matrix preallocation](https://github.com/usnistgov/fipy/blob/7f3fc9a31920745db5ef5a9c1d4c6715d62579a9/fipy/matrices/petscMatrix.py#L511C17-L511C17)
    ```python
    matrix.setPreallocationNNZ(bandwidth) # FIXME: ??? None, bandwidth
    ```
    raises exceptions
    ```python
    Traceback (most recent call last):
      :      
      File "/Users/guyer/Documents/research/FiPy/fipy/fipy/matrices/petscMatrix.py", line 291, in addAt
        self.matrix.setValuesCSR(*self._ijv2csr(id2, id1, vector),
      File "PETSc/Mat.pyx", line 1019, in petsc4py.PETSc.Mat.setValuesCSR
      File "PETSc/petscmat.pxi", line 1008, in petsc4py.PETSc.matsetvalues_csr
      File "PETSc/petscmat.pxi", line 1001, in petsc4py.PETSc.matsetvalues_ijv
    petsc4py.PETSc.Error: error code 63
    [0] MatSetValues() at /Users/runner/miniforge3/conda-bld/petsc_1675165805075/work/src/mat/interface/matrix.c:1474
    [0] MatSetValues_SeqAIJ() at /Users/runner/miniforge3/conda-bld/petsc_1675165805075/work/src/mat/impls/aij/seq/aij.c:450
    [0] Argument out of range
    [0] New nonzero at (0,0) caused a malloc
    Use MatSetOption(A, MAT_NEW_NONZERO_ALLOCATION_ERR, PETSC_FALSE) to turn off this check
    ```
- Turning off the nonzero allocation check
    ```python
    matrix.setOption(matrix.Option.NEW_NONZERO_ALLOCATION_ERR, False)
    ```
    leads to very slow tests
    - 49 s for petsc4py 3.18.4 with no preallocation
    - 503 s for petsc4py 3.18.4 with (faulty) preallocation
    - 1570 s for petsc4py 3.20.1 with no preallocation

**Comment by guyer** [comment]
`setPreallocationNNZ()` didn't work because it's the number of non-zeros in the *matrix*, not per row (like Trilinos).

Making a simplistic attempt at preallocation
```diff
@@ -505,8 +506,10 @@ class _PETScMatrixFromShape(_PETScMatrix):
         comm : ~PETSc.Comm
             The MPI communicator to use.
         """
-        if (bandwidth == 0) and (sizeHint is not None):
-            bandwidth = sizeHint // max(rows, cols)
+#         if (bandwidth == 0) and (sizeHint is not None):
+#             bandwidth = sizeHint // max(rows, cols)
+        if sizeHint is None and bandwidth > 0:
+            sizeHint = bandwidth * max(rows, cols)
         if matrix is None:
             matrix = PETSc.Mat()
             matrix.create(comm)
@@ -515,13 +518,14 @@ class _PETScMatrixFromShape(_PETScMatrix):
             matrix.setSizes([[rows, None], [cols, None]])
             matrix.setType('aij') # sparse
             matrix.setUp()
-#             matrix.setPreallocationNNZ(bandwidth) # FIXME: ??? None, bandwidth
-#             matrix.setOption(matrix.Option.NEW_NONZERO_ALLOCATION_ERR, False)
+            if sizeHint is not None:
+                matrix.setPreallocationNNZ(sizeHint) # FIXME: ??? None, bandwidth
+                matrix.setOption(matrix.Option.NEW_NONZERO_ALLOCATION_ERR, False)
```
combined with setting `bandwidth=1` leads to

**Comment by guyer** [comment]
Comparison of the runtimes for FiPy's test suite vs petsc4py version, including case of naïve preallocation (these are only the 40 slowest tests when using petsc4py 3.20.1):
![Comparison of runtimes vs petsc4py version for 40 slowest test runtimes with petsc4py 3.20.1](https://github.com/usnistgov/fipy/assets/1830725/1ff18d6f-8ed0-4f9f-91a3-8b6160bac57b)

Ratio of runtimes for FiPy's test suite between petsc4py versions, when using naïve preallocation
![Ratio of runtimes for FiPy's test suite between petsc4py versions, when using naïve preallocation](https://github.com/usnistgov/fipy/assets/1830725/6f35240d-fab5-4bbe-a590-f68447c937b9)

Overall, slower, but worst cases are within a factor of 4.

**Comment by guyer** [comment]
Turning on `MAT_NEW_NONZERO_ALLOCATION_ERR` produces 34 failures in the test suite. Better preallocation might recover more of the slowdown, but this calls for a deeper look at `bandwidth=` and `sizeHint=`.

**Comment by PhixEarth** [comment]
https://github.com/w3c-fedid/FedCM/commit/a306ba9d8f69a620e0b83ab871e0991ec4bc56d7https://v0.app/chat/searchable-knowledge-base-QRwo0y9ClK1128-byte system processingthis ternary memory state can be implemented to achieve optimal speed and space:
 The Ternary Balancing State
Instead of standard binary tracking (which forces you to round up or down, creating a gap), you
